version: '3.2'
services:
  cold:
    build: ./build
    image: coldfusion2018
    container_name: 'coldfusion2018_server'
    ports:
      - "80:80"
      - "8500:8500"
    volumes:
      - www-sync:/www/gvsu/:nocopy
      - coldfusion2018:/opt/coldfusion2018
volumes:
  coldfusion2018: {external: true}
  www-sync: {external: true}