version: '3.2'
services:
  cold:
    build: ./build
    image: coldfusion
    container_name: 'coldfusion_server'
    ports:
      - "80:80"
      - "8500:8500"
    volumes:
      - /Users/thomaspikes/Documents/Work/webroot/gvsu:/www/gvsu/:cached
      - coldfusion:/opt/coldfusion2016
volumes:
  coldfusion: {external: true}