version: '3.2'
services:
  unison:
    image: alpine
    container_name: 'unison'
  cold:
    build: ./build
    image: coldfusion
    container_name: 'coldfusion_server'
    ports: 
      - "80:80"
      - "8500:8500"
    volumes:
      - www-sync:/www/gvsu/:nocopy
      - coldfusion:/opt/coldfusion2016
volumes:
  coldfusion:
  www-sync: {external: true}