version: '3.2'
services:
  cold:
    build: ./build
    image: coldfusion2018
    container_name: 'coldfusion2018_server'
    ports:
      - "80:80"
      - "8585:8500"
    volumes:
      - /Users/thomaspikes/Documents/Work/webroot/gvsu:/www/gvsu/:cached
      - coldfusion2018:/opt/coldfusion2018
volumes:
  coldfusion2018: {external: true}